import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import homepage_pic from "../assets/ilustrations/search_job1.svg";
import Button from "../components/Button";
import Navbar from "../components/Navbar";

export default function Home() {
  const [isNavOpen, setIsNavOpen] = useState(false);
  return (
    <>
      <Head>
        <title>Sezonac</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <Navbar/>
        <main className="h-screen flex items-center flex-wrap	justify-between sm:h-full   ">
          <div className="text-left">
            <div>
              <h1 className="text-5xl font-bold leading-normal">
                Tražiš sezonski posao?
                <span className="block">Tražiš radnike?</span>
              </h1>
              <p className="color-red my-8">
                Onda je ovo pravo mjesto za vas. Potraži ili objavi posao!
              </p>
            </div>
            <div className="flex items-center">
              <Button
                name="Objavi Posao"
                textColor="color-white"
                bgColor="bg-blue-500"
                hover="hover:bg-sky-700"
                paddingY="py-5"
                paddingX="px-8"
              />
              <p className="mx-4">
                ili
              </p>
              <Button
                name="Potraži posao"
                textColor="color-white"
                bgColor="bg-transparent"
                hover="hover:bg-sky-700"
                paddingY="py-5"
                paddingX="px-8"
              />
            </div>
          </div>
          <div className="block w-96">
            <Image src={homepage_pic} alt="find-job-image" className="items-center" />
          </div>
        </main>
      </div>
    </>
  );


}
